import type { OvertimeRequestWithUser } from './types'

export const CHARGE_CODE_MAP: Record<string, string> = {
  cc1: 'CC-1001', cc2: 'CC-1002', cc3: 'PROJ-42', cc4: 'PROJ-43', cc5: 'OT-EMRG',
}

export const STEP_UP_ROLE_MAP: Record<string, string> = {
  jr3: 'Senior Operator', jr4: 'Lead Technician', jr5: 'Shift Supervisor',
}

export const MOCK_LOCATIONS_REF = [
  { id: 'loc1', name: 'Site Alpha' },
  { id: 'loc2', name: 'North Yard' },
  { id: 'loc3', name: 'East Terminal' },
]

const TODAY = new Date().toISOString().slice(0, 10)

export const MOCK_OT_REQUESTS_SUPERVISOR: OvertimeRequestWithUser[] = [
  {
    id: 'ot-s1',
    userId: 'u3',
    userName: 'James Tran',
    userJobRole: 'Field Operator',
    userLocationId: 'loc2',
    userLocationName: 'North Yard',
    date: TODAY,
    startTime: '16:00',
    estimatedDurationMinutes: 120,
    chargeCodeId: 'cc3',
    reason: 'Critical phase of North Yard expansion requires shift extension to meet deadline.',
    status: 'REQUESTED',
    createdAt: TODAY,
    updatedAt: TODAY,
  },
  {
    id: 'ot-s2',
    userId: 'u5',
    userName: 'Chen Wei',
    userJobRole: 'Field Operator',
    userLocationId: 'loc3',
    userLocationName: 'East Terminal',
    date: TODAY,
    startTime: '15:30',
    estimatedDurationMinutes: 90,
    chargeCodeId: 'cc4',
    stepUpRoleId: 'jr3',
    reason: 'East Terminal crane maintenance requires senior oversight — no qualified staff available for next shift.',
    status: 'REQUESTED',
    createdAt: TODAY,
    updatedAt: TODAY,
  },
  {
    id: 'ot-s3',
    userId: 'u7',
    userName: 'Kofi Mensah',
    userJobRole: 'Field Operator',
    userLocationId: 'loc1',
    userLocationName: 'Site Alpha',
    date: TODAY,
    startTime: '17:00',
    estimatedDurationMinutes: 60,
    chargeCodeId: 'cc1',
    reason: 'Shift handover delayed due to incoming team transport issues.',
    status: 'REQUESTED',
    createdAt: TODAY,
    updatedAt: TODAY,
  },
  {
    id: 'ot-s4',
    userId: 'u4',
    userName: 'Maria Santos',
    userJobRole: 'Senior Operator',
    userLocationId: 'loc2',
    userLocationName: 'North Yard',
    date: '2026-03-12',
    startTime: '17:00',
    estimatedDurationMinutes: 90,
    chargeCodeId: 'cc5',
    stepUpRoleId: 'jr3',
    reason: 'Emergency pump failure required immediate response and repair.',
    status: 'APPROVED',
    reviewedBy: 'Sandra Okafor',
    reviewedAt: '2026-03-12T09:30:00Z',
    createdAt: '2026-03-12',
    updatedAt: '2026-03-12',
  },
  {
    id: 'ot-s5',
    userId: 'u3',
    userName: 'James Tran',
    userJobRole: 'Field Operator',
    userLocationId: 'loc2',
    userLocationName: 'North Yard',
    date: '2026-03-10',
    startTime: '16:30',
    estimatedDurationMinutes: 60,
    chargeCodeId: 'cc2',
    reason: 'Routine maintenance overrun due to unexpected corrosion found during inspection.',
    status: 'REJECTED',
    reviewedBy: 'Sandra Okafor',
    reviewedAt: '2026-03-10T11:00:00Z',
    reviewNotes: 'Schedule follow-up maintenance for next week instead.',
    createdAt: '2026-03-10',
    updatedAt: '2026-03-10',
  },
  {
    id: 'ot-s6',
    userId: 'u6',
    userName: 'Priya Nair',
    userJobRole: 'Field Operator',
    userLocationId: 'loc1',
    userLocationName: 'Site Alpha',
    date: '2026-03-07',
    startTime: '16:00',
    estimatedDurationMinutes: 180,
    chargeCodeId: 'cc4',
    stepUpRoleId: 'jr4',
    reason: 'East Terminal upgrade milestone — concrete pour cannot be interrupted mid-process.',
    status: 'APPROVED',
    reviewedBy: 'Sandra Okafor',
    reviewedAt: '2026-03-07T07:45:00Z',
    createdAt: '2026-03-07',
    updatedAt: '2026-03-07',
  },
]
